@startuml

class Education {
    EducationID : int
    Title : str
    EducationType : EduType
    Duration : int
    Semesters : Semester List
}

class Schedule{
    Classes : Class List
    Date : datetime
    updateSchedule()
    viewSchedule()
    proposeSchedule()
}

class Location{
    Address : Address
    RoomNumber : str
    LocationType : str
    Capacity : int
}

class Course{
    Schedule : Schedule
    ECTS : int
    CourseID : CID
    EnrolledStudents : Student List
    Responsible : Administration
}

class Class{
    Time : datetime
    ClassLocation : Location
    ClassType : CType
    Teachers : Teacher List
    EnrolledStudents : Student List
    setLocation()
    setClassType()
}

class Login{
    LoginType : LType
    UserType : UType
    authenticate()
}

class User{
    UserSchedule : Schedule
    PersonalInfo : PInfo
    ContactInfo : CInfo
}

class Semester{
    Courses : Course List
    StartDate : datetime
}

class Student{
    Enrollment : Education
    UserSchedule : Schedule
    PersonalInfo : str
    ContactInfo : str
    setInfo()
    updateInfo()
}

class Teacher{
    UserSchedule : Schedule
    PersonalInfo : str
    ContactInfo : str
    CourseAffiliations : Course List
}

User --o Schedule
Course --o Schedule
Student --o Schedule
Teacher --o Schedule

Education --o Semester

Class --o Location

User <|-- Student
User <|-- Teacher

Semester --> Course
Schedule --o Class

@enduml

