@startuml ClassDiagram

class Education {
    EducationID : Int
    Title : String
    EducationType : EduType
    Duration : Int
    Semesters : Semester[]
}

class Schedule{
    ScheduleID : Int
    StartDate : datetime
    EndDate : datetime
    ScheduleStatus : ScheduleStatus
    AdminID : Int
    EducationID : Int
    ProposeSchedule()
    CreateSchedule()
    UpdateSchedule()
    ViewSchedule()
}

class Location{
    Address : Address
    RoomID : Int
    LocationType : LocationType
    Capacity : Int
}

class Course{
    ECTS : Float
    CourseID : CID
    Teacher : Teacher
    Location : Location
}

class Class{
    Time : datetime
    ClassLocation : Location
    ClassType : CType
    Teachers : Teacher[]
    EnrolledStudents : Student[]
    setLocation()
    setClassType()
}

' class Login{
'     LoginType : LogType
'     UserType : UType
'     authenticate()
' }

class User{
    FirstName : String
    LastName : String
    Mail : String
    PhoneNumber : Int
    UserID: UserID
}

' class Semester{
'     Courses : Course[]
'     StartDate : Datetime
' }

class Student{
    Enrollment : Education
    ViewSchedule()
}

class Teacher{
    TeacherID
    SaveProposedSchedule()
    SendProposedSchedule()
    CreateSchedule()
    ViewSchedule()
}

class Admin{
    InputInfo()
}

class TimeFrame{
    ScheduleID : Int
    StartTime : datetime
    EndTime : datetime
    Weekday : Day
    UpdateTimeFrame()
    DeleteTimeFrame()
}

class CourseSecretary{
    CreateSchedule()
}

' User"1" o-- "1" Schedule : has a
Course"1" --o "1" Schedule : has a
' Student"1" o-- "1" Schedule : has a
' Teacher"1" o-- "1" Schedule : has a

' Education"1" *-- "4..6" Semester : contains

Class "1" o-- "1..*"Location : has a

User <|-- Student : inherits
User <|-- Teacher : inherits
User <|-- Admin : inherits
User <|-- CourseSecretary : inherits

' Semester"1" *-- "1..*" Course : contains
Course"1" *-- "0..*" Class : contains
Course"1" *-- "0..*" TimeFrame : contains
Teacher"1" --o "1" Course : teaches
Student"1" o-- "1" Education : enrolled in
Schedule --o Education 

' Login "1" -- "1" User : login

@enduml

