@startuml
left to right direction
Student as std #line:green
Teacher as tc #line:blue
TA as ta #line:deeppink
CourseSecretary as cs
Admin as adm

package Uniflow{
usecase "Create Schedule" as 1
usecase "Request Change" as 2
usecase "Change Schedule" as 3
usecase "View Schedule" as 4
}

std--2 #line:green
std--4 #line:green
tc--1 #line:blue
tc--2 #line:blue
tc--4 #line:blue
ta--2 #line:deeppink
ta--4 #line:deeppink
1--cs
3--cs
4--cs
2--adm
3--adm
4--adm


@enduml